name: bamboohr-attendance
description: Retrieve a list of people who are out of office from BambooHR
author: Erin Grasmick (egrasmick@wisc.edu)
inputs:
  bamboohr_subdomain:
    description: "BambooHR subdomain"
    default: ""
    required: true
  bamboohr_api_token:
    description: "BambooHR API token"
    default: ""
    required: true
  people_in_today:
    description: "Set to true to include people who are in the office today"
    default: ""
    required: true
  people_out_today:
    description: "Set to true to include people who are in the office today"
    default: ""
    required: true
  bamboohr_fields:
    description: "any fields, comma separated, you want to retrieve from the BambooHR API"
    default: "firstName,lastName"
    required: true
  from_date:
    description: "A linux `date` command to run to obtain the start date of attendance gathering"
    default: "date"
    required: false
  to_date:
    description: "A linux `date` command to run to obtain the end date of attendance gathering"
    default: "date"
    required: false
runs:
  using: docker
  image: 'Dockerfile'
branding:
  icon: 'message-square'
  color: 'gray-dark'
